version: "2"
services:
  web:
    build: .
    ports:
      - "3000:3000"
    restart: always
    links:
      - mongo
  mongo:
    image: mongo
    restart: always
    volumes:
      - "./server/databases:/data/db"
    ports:
      - "27017:27017"